f=open('f1.txt', 'w')
a = f.write(input())
f.close()
f=open('f1.txt', 'r')
a = f.read()
q=open('f2.txt', 'w')
q.write(a[::-1])
f.close()
q.close()
print(open('f1.txt').read())
print(open('f2.txt').read())
